### ISSUE TITLE
Schedule page crash after logging out and then logging in to the app

### ISSUE THREAD

**Issue by camillebrulotte** [ApplETS/Notre-Dame#107]
**Describe the bug**
In the schedule view model, 'toLanguageTag' seems to be called on null after logging out and then logging in to the app.

**To Reproduce**
1. Logging in to the app
2. Logout
3. Logging in to the app
4. Go to 'Schedule'

**Expected behavior**
We should be able to see the schedule page after logging out and then logging in to the app.

**Screenshots**
<img width="300" alt="Capture d’écran, le 2021-04-26 à 21 46 29" src="https://user-images.githubusercontent.com/37625944/116172490-dd3f6c00-a6d8-11eb-8720-1a34cd34b0e3.png">

**Comment by AlexandreMarkus** [comment]
@camillebrulotte Good issue!!! Got same on Android

**Comment by AlexandreMarkus** [comment]
If you change the language of the app in [MORE] it seems to work again

**Comment by apomalyn** [comment]
Do you have the latest version of master? The fix I did with #100 should have taken care of that. Check the [main file at line 44](https://github.com/ApplETS/Notre-Dame/blob/master/lib/main.dart#L44) when the locale is null, there should have a locale set.

**Comment by apomalyn** [comment]
@camillebrulotte this line is called before the application start :) you can't hot reload it ^^' But you are right there is a problem when the user log out and try to log in without killing the application. Because when we log out, we clear the Preferences...I will move this section of the code directly in the preferences settings to avoid any trouble.
