### ISSUE TITLE
FAQ or message more explicit

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#194]
**Describe the issue** 
```Aucun accès aux notes des cours de la session en cours.```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-567213613.png?raw=true)

**Device Infos** 
- **Version:** 4.2.3 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1631981526 
- **Platform operating system:** ios 
- **Platform operating system version:** 14.8

**Comment by apomalyn** [comment]
The club isn't concern about that.

**Comment by MysticFragilist** [comment]
Personally, I think the message is clear enough.

Just to be sure, we don't have the evaluations list if we don't have at least one grade, right?

**Comment by apomalyn** [comment]
No, the evaluation list is available as soon as the teacher created it on Signets. In most cases, teachers don't create it and enter the grades one by one this is why you see the grades pop in one after another 😄 

Don't hesitate to tell your teachers to create it because they have it (on planets!!!) 😄

**Comment by MysticFragilist** [comment]
Ahh I see. Then, I have 3 ideas that I don't know which one is best:

1- I'm wondering if instead of putting a button retry (which is generally used a lot when there is an error), we could just make a go back button. It would maybe give a less frightening look at that page. 
I don't know it's just an idea, but I could easily imagine somebody spamming the button retry just to make it work until he gets frustrated because there is a "bug" that don't let him access its grades.

2- I find the message to be okay! It's clear and concise and give the info it needs to give. Though, we could add a small message under guiding the user on why there is an issue: "maybe the professor did not add evaluations yet to this class." like you mentioned.

3- Or we could show the page as usual, but without any data in grade, average or median: the top info. It would be display but empty and under where the evaluations are supposed to be, we show the same message as the one in the current page when empty.

Let me know if any of those solution could work!

**Comment by MysticFragilist** [comment]
This was resolved by camille's PR, closing it
