### ISSUE TITLE
'Session' should be 'Semester'

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#408]
**Describe the issue** 
```"session progress" doit être plutôt "semester progress" parce que "session" en anglais veut dire une séance.```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-192611387.png?raw=true)

**Device Infos** 
- **Device:** BE2026 
- **Version:** 4.9.1 
- **Connectivity:** ConnectivityResult.mobile 
- **Build number:** 1645466811 
- **Platform operating system:** android 
- **Platform operating system version:** BE2026_17_211229

**Comment by MysticFragilist** [comment]
This is a great point! 👍we should check everywhere we call it 'session'

**Comment by dev-SsyncC** [comment]
Hi, I'm trying to work on this issue but have this error.
can you help me so I can proceed?
![Screenshot 2022-03-02 164553](https://user-images.githubusercontent.com/60522175/156352021-26b3160b-47e1-437f-825b-b1292aa08971.jpg)

**Comment by MysticFragilist** [comment]
> Hi, I'm trying to work on this issue but have this error.
> can you help me so I can proceed?
> ![Screenshot 2022-03-02 164553](https://user-images.githubusercontent.com/60522175/156352021-26b3160b-47e1-437f-825b-b1292aa08971.jpg)
> 

Hi! Did you try to update your flutter version? Maybe doing `flutter channel stable` and then `flutter upgrade` would fix this issue. Lmk if it helps!

**Comment by dev-SsyncC** [comment]
Yes, it did work. thanks

**Comment by dev-SsyncC** [comment]
How can I resolve this?
![goog](https://user-images.githubusercontent.com/60522175/156543023-07f57af6-311d-4728-af12-d6d6f18d324a.jpg)

**Comment by MysticFragilist** [comment]
Hi! Since you are not a member of App|ETS, you will need to generate a google-service.json file for a custom firebase project and downloading the file to put in the specified location. If you decide to apply to be part of the club, we can provide you a script to auto decrypt those files (the part ./env_var.sh in README.md).

If you decide to join us, you will have to do a small tutorial on flutter (~1 hour).

to create a firebase project: https://firebase.google.com/
to be part of our team: https://clubapplets.ca/contact
