### ISSUE TITLE
Emergency procedures webview doesn't follow the theme

### ISSUE THREAD

**Issue by AlexandreMarkus** [ApplETS/Notre-Dame#56]
**Describe the bug**
The theme of the webview in emergency follow the phone theme instead of the one from the app.
The list of emergency procedures should be white or black depending on the theme

**To Reproduce**
1. Go to ETS
2. Click on Security
3. Scroll down to Emergency procedures
4. Click on one item

**Expected behavior**
Webview should follow the theme of the app and not the theme of the phone.
Emergency procedures should not be blue.

**Screenshots**
![image](https://user-images.githubusercontent.com/59664238/110267800-88139380-7f8e-11eb-9fc5-269e1401c387.png)
![image](https://user-images.githubusercontent.com/59664238/110267819-92ce2880-7f8e-11eb-9cd7-2c596d0f926c.png)

**Comment by MysticFragilist** [comment]
I don't know if it has been dealt with already but on my phone (samsung S10e) there is no issue visible. When I changed to light, the security emergency view is light even if my system is dark (tested the other way around and it's working also). However, I do see the blue link which I will look into. Otherwise can you tell me if you are still able to reproduce it and which os/phone are you using to have the expected issue?

**Comment by apomalyn** [comment]
@MysticFragilist I wasn't able to reproduce the bug with the theme either. @AlexandreMarkus is this bug still real?

**Comment by AlexandreMarkus** [comment]
@apomalyn @MysticFragilist you guys are right, it doesn't seem to be a bug anymore. The only thing to be done here, is to change the color of emergency links
